default: &default
  adapter: postgresql
  encoding: utf8

local_default: &local_default
  <<: *default
  min_messages: warning
  pool: 10
  timeout: 5000
  host: localhost

development:
  <<: *local_default
  database: impacked-development

test:
  <<: *local_default
  database: impacked-test

staging:
  <<: *default
  pool: 10
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  pool: 25
  url: <%= ENV['DATABASE_URL'] %>
